#!/bin/bash -eux

# This example makes some assumptions about the system (such as NPM being installed), which
# internally at Dropbox are handled by build system puppet configurations (and a few helper)
# scripts.

# Your system should be configured with a base image as such, and then run with something like:
# sudo ./changes-lxc-wrapper \
#     --project=changes \
#     --script=examples/changes

echo `whoami`
echo $PATH

sudo apt-get install -y python-software-properties software-properties-common

sudo add-apt-repository -y ppa:chris-lea/node.js
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update -y

sudo apt-get install -y git nodejs build-essential python-setuptools redis-server postgresql python-dev libpq-dev libevent-dev libxml2-dev libxslt-dev

if [ ! -e ./source/ ]; then
	git clone https://github.com/dropbox/changes.git ./source/
	pushd source
else
	pushd source
	git pull https://github.com/dropbox/changes.git master
fi

npm --version

sudo npm install -g bower
sudo easy_install -U pip
sudo pip install virtualenv

virtualenv --no-site-packages `pwd`/env

export PATH=`pwd`/env/bin:$PATH

sudo -u postgres createuser -s `whoami` --no-password || true
sudo -u postgres createdb changes || true
